Refactor leftwm crash management
leftwm/leftwm pull request #832
Opened 2022-09-09 13:24 UTC by TornaxO7

# Description

Currently `leftwm` just creates a new session if the current session exits which might be undesired because we are currently ignoring the reason *why* the session exited. The session might crash if the worker paniced which means that there's an error/a bug in the code of `leftwm`.

A little more context: I noticed this issue when I tried to run my logger. It crashed but leftwm kept creating new sessions.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Updated user documentation:

Not needed

**Note: Manual page changes must be performed in a commit, not in this PR section.**

# Checklist:

- [X] Ran `make test-full` locally with no errors or warnings reported
- [X] Manual page has been updated accordingly
- [X] Wiki pages have been updated accordingly (to perform **after** merge)

2022-09-09 13:28 UTC, TornaxO7 commented
Eh, I don't understand the failing check o.O @AethanFoot @VuiMuich @hertg  can anyone of you explain what I'm doing wrong?

2022-09-09 15:38 UTC, hertg commented
> Eh, I don't understand the failing check o.O @AethanFoot @VuiMuich @hertg can anyone of you explain what I'm doing wrong?

You are not doing anything wrong, you can ignore the issue.
Problem is that the token used in this workflow is not passed to the action because this PR comes from a fork. But it is an error anyway that this action tries to run on PRs. I'll fix that later :)

2022-09-09 15:44 UTC, hertg commented
I just removed it

2022-09-09 18:12 UTC, TornaxO7 commented
> I just removed it

Is it possible that you restart my checks? Because otherwise I need to look for some changes to push again.

2022-09-09 18:23 UTC, VuiMuich commented
> > I just removed it
> 
> Is it possible that you restart my checks? Because otherwise I need to look for some changes to push again.

Just tried that, I guess this might just stick with this PR, unless there is a way to remove checks manually I am failing to find.
Sorry but we might just have to ignore this failed check.

2022-09-09 18:23 UTC, TornaxO7 commented
> Just tried that, I guess this might just stick with this PR, unless there is a way to remove checks manually I am failing to find.
Sorry but we might just have to ignore this failed check.

could it be that I have to pull from upstream?

2022-09-09 18:27 UTC, TornaxO7 commented
I just saw that I forgot to test it. I'll converting it back from a draft to a PR if I run it a bit.

2022-09-09 18:35 UTC, TornaxO7 commented
Alright, works fine! @AethanFoot @hertg @VuiMuich ready for review!

2022-09-09 18:45 UTC, VuiMuich requested changes

2022-09-09 18:45 UTC, VuiMuich commented on leftwm/src/bin/leftwm.rs
> +        no_error_occured = evaluate_session(&mut leftwm_session) != SessionStatus::Error;
You have a double negative logic here. Wouldn't it be nicer to read with:
```suggestion
        error_occured = evaluate_session(&mut leftwm_session) == SessionStatus::Error;
```

2022-09-09 18:45 UTC, VuiMuich commented on leftwm/src/bin/leftwm.rs
> +    if !no_error_occured {
follow up from above:
```suggestion
    if error_occured {
```

2022-09-09 18:45 UTC, VuiMuich commented on leftwm/src/bin/leftwm.rs
> +    while no_error_occured {
Ofc at some point we need to have some negative logic:
```suggestion
    let mut error_occured = false;
    while !error_occured {
```

2022-09-09 18:45 UTC, VuiMuich commented on leftwm/src/bin/leftwm.rs
> +    }
Can this be refactored in a match case with `Ok() if ..`
How are we acting on `DidNotStart` anyways? We maybe want to add some commentary/doc about the StessionStatus and its implications.

2022-09-09 18:45 UTC, VuiMuich commented on leftwm/src/bin/leftwm.rs
> +    println!("NOTE: You can restart leftwm with `startx`.");
Can you please refactor to a single invocation of `println!` macro?

2022-09-09 19:03 UTC, TornaxO7 commented
I adjusted the code a little bit @VuiMuich

2022-09-09 19:13 UTC, TornaxO7 commented
@VuiMuich sorry, `no_error_occured` is now refactored as well!

2022-09-09 19:14 UTC, VuiMuich approved these changes

2022-09-09 19:17 UTC, VuiMuich commented
One thing I wanted to ask but forgot, as I can't test run this right now: does this return the exit codes, so the terminal recieve those?

2022-09-09 19:18 UTC, TornaxO7 commented
> One thing I wanted to ask but forgot, as I can't test run this right now: does this return the exit codes, so the terminal recieve those?

No the `leftwm.rs` binary just looks

2022-09-09 19:28 UTC, VuiMuich commented
> > One thing I wanted to ask but forgot, as I can't test run this right now: does this return the exit codes, so the terminal recieve those?
> 
> 
> 
> No the `leftwm.rs` binary just evaluates the exit-status from `leftwm-worker` and exits normally (with code 0), but I can add this as well if you want.

Yes I think if we exit on error we should actually exit with 1

2022-09-09 19:29 UTC, TornaxO7 commented
> > > One thing I wanted to ask but forgot, as I can't test run this right now: does this return the exit codes, so the terminal recieve those?
> > 
> > 
> > No the `leftwm.rs` binary just evaluates the exit-status from `leftwm-worker` and exits normally (with code 0), but I can add this as well if you want.
> 
> Yes I think if we exit on error we should actually exit with 1

Or should `leftwm` even return the exit code from the session?

2022-09-09 19:50 UTC, VuiMuich commented
Yes, when we exit because the worker exited on error, the main bin should not hide that and also exit on 1, imo.

2022-09-09 19:51 UTC, TornaxO7 commented
> Yes, when we exit because the worker exited on error, the main bin should not hide that and also exit on 1, imo.

But couldn't it happen that the worker exited with even another code like 2 or 17 (for whatever reason)?

2022-09-12 03:34 UTC, mautamu approved these changes
Seems like this is a good way of handling crash-worthy errors; though perhaps in the future a notify-send and attempt to repair might also be in order.

2022-09-12 21:02 UTC, TornaxO7 commented
@AethanFoot there's still this build error and I don't really know what I should do with it :sweat_smile: do you have any suggestions?

2022-09-12 21:06 UTC, AethanFoot commented
Looks like the starting and killing lefthk accidentally got refactored out (make sure to add the lefthk feature checks).

2022-09-12 21:09 UTC, TornaxO7 commented
Looks like that it's fine now :thinking:

2022-09-24 17:08 UTC, VuiMuich commented on leftwm/src/bin/leftwm.rs
> -        kill_lefthk_session(&mut lefthk_session);
This is needed I believe, or did I simply miss, where it got moved to?

2022-09-24 17:10 UTC, VuiMuich commented on leftwm/src/bin/leftwm.rs
> -        let mut lefthk_session = start_lefthk_session(&current_exe);
Also needed. I think this is why CI fails.

2022-09-25 06:26 UTC, VuiMuich approved these changes

2022-09-25 12:29 UTC, hertg approved these changes
Have no time to test-run right now, but looks fine code wise

2022-09-25 20:18 UTC, merged

2022-10-25 17:26 UTC, VuiMuich commented
As there is a number of reports, that users get thrown out of their session, when only supposedly recoverable things crash I suspect this PR might be the most probable culprit.
Maybe we should indeed return to a more robust approach and only log the error state of the child.
@TornaxO7 would you have time to look into this?

2022-10-25 19:45 UTC, TornaxO7 commented
@VuiMuich may I ask if you can provide me a link to try to reproduce the issues please?

2022-10-25 19:59 UTC, VuiMuich commented
Most of them got reported on discord, some even in dm, but I asked the latest one to report as an issue.